---
name: "JellyChat"
guid: "d3e50ec8-d597-488a-828f-db31d69c095a"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.JellyChat.dll"
changelog: >
  changelog
